In [1]:
import numpy as np
import pandas as pd 
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("new_test_set1.csv")

In [3]:
df.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [4]:
X = df.drop('Fertilizer Name', axis=1).copy

In [5]:
y = df['Fertilizer Name'].copy()
X = df.drop('Fertilizer Name', axis=1).copy() # Add parentheses to call the copy method

In [6]:
y = df['Fertilizer Name'].copy()
X = df.drop('Fertilizer Name', axis=1).copy

In [8]:
# In cell 139 and other cells where .copy() is used, add parentheses:
X = df.drop('Fertilizer Name', axis=1).copy()

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3,4])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
X[0]

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., 26., 52., 38., 37.,  0.,  0.])

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True, random_state=42)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train[0]


array([-0.48181206,  1.98206242, -0.59408853, -0.50452498, -0.41169348,
       -0.24806947, -0.33601075, -0.33601075, -0.17277369, -0.36214298,
       -0.24806947, -0.36214298,  3.24037035, -0.43549417, -0.24806947,
       -0.36214298, -1.50323411, -1.54242294, -1.00710689,  0.46072126,
       -0.57643157,  0.09092764])

In [14]:
from sklearn.ensemble import ExtraTreesClassifier # Import ExtraTreesClassifier instead of ExtraTreeClassifier
classifier = ExtraTreesClassifier(n_estimators=100, criterion='gini', random_state=42) # Use ExtraTreesClassifier
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3 0 0 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 5 1 0]
 [0 0 0 0 0 7 0]
 [0 0 0 0 0 0 7]]


0.9666666666666667

In [16]:
classifier.score(X_test, y_test)


0.9666666666666667

In [17]:
from sklearn.preprocessing import LabelEncoder


In [18]:
encode_soil = LabelEncoder()
df['Soil Type'] = encode_soil.fit_transform(df['Soil Type'])

#creating the DataFrame
Soil_Type = pd.DataFrame(zip(encode_soil.classes_,encode_soil.transform(encode_soil.classes_)),columns=['Original','Encoded'])
Soil_Type = Soil_Type.set_index('Original')
Soil_Type

Encoded
Original         
Black           0
Clayey          1
Loamy           2
Red             3
Sandy           4

In [19]:
encode_crop =  LabelEncoder()
df['Crop Type'] = encode_crop.fit_transform(df['Crop Type'])

#creating the DataFrame
Crop_Type = pd.DataFrame(zip(encode_crop.classes_,encode_crop.transform(encode_crop.classes_)),columns=['Original','Encoded'])
Crop_Type = Crop_Type.set_index('Original')
Crop_Type

Encoded
Original            
Barley             0
Cotton             1
Ground Nuts        2
Maize              3
Millets            4
Oil seeds          5
Paddy              6
Pulses             7
Sugarcane          8
Tobacco            9
Wheat             10

In [20]:
encode_ferti = LabelEncoder()
df['Fertilizer Name'] = encode_ferti.fit_transform(df['Fertilizer Name'])

#creating the DataFrame
Fertilizer = pd.DataFrame(zip(encode_ferti.classes_,encode_ferti.transform(encode_ferti.classes_)),columns=['Original','Encoded'])
Fertilizer = Fertilizer.set_index('Original')
Fertilizer

Encoded
Original         
10-26-26        0
14-35-14        1
17-17-17        2
20-20           3
28-28           4
DAP             5
Urea            6

In [21]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop('Fertilizer Name',axis=1),df['Fertilizer Name'],test_size=0.2,random_state=1)
print('Shape of Splitting :')
print('x_train = {}, y_train = {}, x_test = {}, y_test = {}'.format(x_train.shape,y_train.shape,x_test.shape,y_test.shape))

Shape of Splitting :
x_train = (79, 8), y_train = (79,), x_test = (20, 8), y_test = (20,)


In [22]:
x_train.info()


<class 'pandas.core.frame.DataFrame'>
Index: 79 entries, 2 to 37
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temparature  79 non-null     int64
 1   Humidity     79 non-null     int64
 2   Moisture     79 non-null     int64
 3   Soil Type    79 non-null     int64
 4   Crop Type    79 non-null     int64
 5   Nitrogen     79 non-null     int64
 6   Potassium    79 non-null     int64
 7   Phosphorous  79 non-null     int64
dtypes: int64(8)
memory usage: 5.6 KB


In [23]:
rand = ExtraTreesClassifier(random_state = 42)
rand.fit(x_train,y_train)

ExtraTreesClassifier(random_state=42)

In [24]:
pred_rand = rand.predict(x_test)


In [25]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

params = {
    'n_estimators':[300,400,500],
    'max_depth':[5,10,15],
    'min_samples_split':[2,5,8]
}
grid_rand = GridSearchCV(rand,params,cv=3,verbose=3,n_jobs=-1)

grid_rand.fit(x_train,y_train)

pred_rand = grid_rand.predict(x_test)

print(classification_report(y_test,pred_rand))

print('Best score : ',grid_rand.best_score_)
print('Best params : ',grid_rand.best_params_)

Fitting 3 folds for each of 27 candidates, totalling 81 fits
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         6

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

Best score :  1.0
Best params :  {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 300}


In [26]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

# ... (your existing code for data loading, preprocessing, etc.) ...

# Define the parameter grid for GridSearchCV
params = {
    'n_estimators': [300, 400, 500],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 8]
}

# Initialize GridSearchCV
grid_rand = GridSearchCV(rand, params, cv=3, verbose=3, n_jobs=-1)

# Fit the model using GridSearchCV
grid_rand.fit(x_train, y_train)

# Make predictions on the test set
pred_rand = grid_rand.predict(x_test)

# Calculate and print the accuracy score in percent
accuracy = accuracy_score(y_test, pred_rand)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Print the classification report
print(classification_report(y_test, pred_rand))

# Print the best score and best parameters
print('Best score:', grid_rand.best_score_)
print('Best params:', grid_rand.best_params_)

Fitting 3 folds for each of 27 candidates, totalling 81 fits
Accuracy: 100.00%
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         6

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

Best score: 1.0
Best params: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 300}


In [28]:
# prompt: user input prediction system with accuracy

import numpy as np
import pandas as pd 
import warnings
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

warnings.filterwarnings("ignore")

# Load the dataset (replace 'new_test_set1.csv' with the actual file name)
df = pd.read_csv("new_test_set1.csv")

# Preprocessing (Label Encoding)
encode_soil = LabelEncoder()
df['Soil Type'] = encode_soil.fit_transform(df['Soil Type'])

encode_crop = LabelEncoder()
df['Crop Type'] = encode_crop.fit_transform(df['Crop Type'])

encode_ferti = LabelEncoder()
df['Fertilizer Name'] = encode_ferti.fit_transform(df['Fertilizer Name'])

# Split data
x_train, x_test, y_train, y_test = train_test_split(
    df.drop('Fertilizer Name', axis=1),
    df['Fertilizer Name'],
    test_size=0.2,
    random_state=1
)

# Model Training
rand = ExtraTreesClassifier(random_state=42)
rand.fit(x_train, y_train)

# Hyperparameter Tuning (GridSearchCV)
params = {
    'n_estimators': [300, 400, 500],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 8]
}
grid_rand = GridSearchCV(rand, params, cv=3, verbose=3, n_jobs=-1)
grid_rand.fit(x_train, y_train)

# Prediction and Evaluation
pred_rand = grid_rand.predict(x_test)
print(classification_report(y_test, pred_rand))
print('Best score : ', grid_rand.best_score_)
print('Best params : ', grid_rand.best_params_)

# User Input Prediction System
def predict_fertilizer():
    temperature = float(input("Enter Temperature: "))
    humidity = float(input("Enter Humidity: "))
    moisture = float(input("Enter Moisture: "))
    soil_type = input("Enter Soil Type (from the encoded list): ")
    crop_type = input("Enter Crop Type (from the encoded list): ")
    nitrogen = float(input("Enter Nitrogen content: "))
    potassium = float(input("Enter Potassium content: "))
    phosphorous = float(input("Enter Phosphorous content: "))

    try:
        soil_type = int(soil_type) #Convert the soil type to an integer
        crop_type = int(crop_type)  #Convert the crop type to an integer

        user_input = pd.DataFrame({
            'Temparature': [temperature],
            'Humidity ': [humidity],
            'Moisture': [moisture],
            'Soil Type': [soil_type],
            'Crop Type': [crop_type],
            'Nitrogen': [nitrogen],
            'Potassium': [potassium],
            'Phosphorous': [phosphorous]
        })
        
        prediction = grid_rand.predict(user_input)
        predicted_fertilizer = encode_ferti.inverse_transform(prediction)[0] #Decode prediction
        print(f"Predicted Fertilizer: {predicted_fertilizer}")
        accuracy = grid_rand.score(x_test, y_test)
        print(f"Model Accuracy: {accuracy * 100:.2f}%")

    except ValueError: # Handles potential errors in input format
        print("Invalid input. Please enter numeric values for Soil Type and Crop Type")

predict_fertilizer()


Fitting 3 folds for each of 27 candidates, totalling 81 fits
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         6

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

Best score :  1.0
Best params :  {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 300}


Enter Temperature:  33
Enter Humidity:  64
Enter Moisture:  34
Enter Soil Type (from the encoded list):  1
Enter Crop Type (from the encoded list):  7
Enter Nitrogen content:  38
Enter Potassium content:  0
Enter Phosphorous content:  0


Predicted Fertilizer: Urea
Model Accuracy: 100.00%
[CV 2/3] END max_depth=5, min_samples_split=2, n_estimators=300;, score=1.000 total time=   0.2s
[CV 3/3] END max_depth=5, min_samples_split=2, n_estimators=500;, score=1.000 total time=   0.5s
[CV 2/3] END max_depth=5, min_samples_split=8, n_estimators=300;, score=0.962 total time=   0.2s
[CV 3/3] END max_depth=5, min_samples_split=8, n_estimators=500;, score=1.000 total time=   0.4s
[CV 2/3] END max_depth=10, min_samples_split=5, n_estimators=300;, score=1.000 total time=   0.2s
[CV 3/3] END max_depth=10, min_samples_split=5, n_estimators=500;, score=1.000 total time=   0.3s
[CV 1/3] END max_depth=15, min_samples_split=2, n_estimators=300;, score=0.963 total time=   0.2s
[CV 1/3] END max_depth=15, min_samples_split=2, n_estimators=500;, score=1.000 total time=   0.3s
[CV 2/3] END max_depth=15, min_samples_split=5, n_estimators=500;, score=1.000 total time=   0.3s
[CV 1/3] END max_depth=15, min_samples_split=8, n_estimators=500;, scor